### ISSUE TITLE
Предварительные Правки Глава 7

### ISSUE THREAD

**Issue by CrewGTW** [Regnaris/RRS-visualnovel#20]
![01-11-2018 165044](https://user-images.githubusercontent.com/44586196/47930345-bc697780-dedc-11e8-92ff-bd5c0957b4e2.jpg)

Разделить на два фрейма с :"Они дали ему...:

![01-11-2018 165337](https://user-images.githubusercontent.com/44586196/47930349-bd020e00-dedc-11e8-82a2-c65fd4809920.jpg)

Изображения Вирявы нет. ( и его вообще нет в сцене)

![01-11-2018 165414](https://user-images.githubusercontent.com/44586196/47930350-bd020e00-dedc-11e8-94c6-5661d903f557.jpg)

Паузу убрать.

![01-11-2018 165533](https://user-images.githubusercontent.com/44586196/47930351-bd9aa480-dedc-11e8-9d48-8b604e7f0f6a.jpg)

"Это... Давай"

![01-11-2018 165606](https://user-images.githubusercontent.com/44586196/47930352-bd9aa480-dedc-11e8-94ba-8620657a82ca.jpg)

Пробел.

![01-11-2018 165731](https://user-images.githubusercontent.com/44586196/47930353-bd9aa480-dedc-11e8-9bd1-31e4fb5a3350.jpg)

Разбить на два фрейма: "Там была..."

![01-11-2018 165815](https://user-images.githubusercontent.com/44586196/47930354-be333b00-dedc-11e8-91d8-54c3bb2e13a3.jpg)

Поменять местами обычный и большой шрифт.

![01-11-2018 165835](https://user-images.githubusercontent.com/44586196/47930355-be333b00-dedc-11e8-8e73-7cca27329823.jpg)

"Да как я могу успокоиться?!" - Эмоцию stefan_awkward

![stefan_awkward](https://user-images.githubusercontent.com/44586196/47930595-752fb680-dedd-11e8-9f84-e2268f6ddbfb.png)

![01-11-2018 165906](https://user-images.githubusercontent.com/44586196/47930357-be333b00-dedc-11e8-9174-63aa970e3244.jpg)

Появился плащ, которого быть не должно.

![01-11-2018 165928](https://user-images.githubusercontent.com/44586196/47930358-be333b00-dedc-11e8-9eae-f3b3c7248990.jpg)

Нет фона.

![01-11-2018 170119](https://user-images.githubusercontent.com/44586196/47930359-becbd180-dedc-11e8-925c-f7081e1ab93e.jpg)

Нет фона.

![01-11-2018 170245](https://user-images.githubusercontent.com/44586196/47930360-becbd180-dedc-11e8-81ba-82b51dcc8080.jpg)

Разбить на фреймы.

"Он... (пауза) Точно не человек!"

"Люди так не могут, у них не бывает такой силы."

![01-11-2018 170323](https://user-images.githubusercontent.com/44586196/47930361-becbd180-dedc-11e8-98f7-03717b7fdc77.jpg)

Паузу убрать.

![01-11-2018 170406](https://user-images.githubusercontent.com/44586196/47930363-becbd180-dedc-11e8-8de8-fa43008db811.jpg)

Разбить:

"Может быть... Стефан просто привык?"

"К ситуациям... (пауза) К существам... (пауза) К самому Жонки?

"Может, он перестал ощущать опасность, Когда адреналин в крови начал сходить на нет,, а страх смерти перестаёт дышать в спину?"

**Comment by Regnaris** [comment]
>Разбить на фреймы.
"Он... (пауза) Точно не человек!"
"Люди так не могут, у них не бывает такой силы."

Фразу нашел и разбил на две реплики, но картинка у тебя стоит другая. Случайно ошибся или еще какую правку упомянуть забыл?

**Comment by Regnaris** [comment]
Все правки внесены, закрываю.
