### ISSUE TITLE
Правки 8-12 глава по версии 3.0

### ISSUE THREAD

**Issue by CrewGTW** [Regnaris/RRS-visualnovel#28]
Это говорит Жонки.

![15-11-2018 102303](https://user-images.githubusercontent.com/44586196/48604255-4fe58280-e98a-11e8-9312-dadbb9188dff.jpg)

Не надо делить эту фразу паузой.

![15-11-2018 103341](https://user-images.githubusercontent.com/44586196/48604256-4fe58280-e98a-11e8-8153-80dbe814b561.jpg)

Шеф... (пауза) Я знал, вы более добрый, чем кажетесь на первый взгляд.

![15-11-2018 103352](https://user-images.githubusercontent.com/44586196/48604257-4fe58280-e98a-11e8-8cb1-449e43ac876d.jpg)

поправится

![15-11-2018 103949](https://user-images.githubusercontent.com/44586196/48604258-4fe58280-e98a-11e8-95d8-6d7e4284f467.jpg)

Косяк текста.

Да и вообще можно разбить на два фрейма. До "твоему хозяину недолго осталось"

"Через пару недель он уже будет поглощён."

![15-11-2018 104157](https://user-images.githubusercontent.com/44586196/48604259-507e1900-e98a-11e8-9ec8-698625462a3d.jpg)

Разбить на моменте:

"Её невозможно ни использовать..."

![15-11-2018 104553](https://user-images.githubusercontent.com/44586196/48604260-507e1900-e98a-11e8-8ae8-a77c5e17d8ef.jpg)

Текст разбит криво.

"Помимо прочего" на следующий фрейм.

![15-11-2018 104625](https://user-images.githubusercontent.com/44586196/48604261-507e1900-e98a-11e8-80ae-f0d2c6dfcddc.jpg)

Тут разбить с "Каждое последующее поколение"

![15-11-2018 104631](https://user-images.githubusercontent.com/44586196/48604263-5116af80-e98a-11e8-9b7d-a49a202cbc3a.jpg)

Разбить. "С изменением жизненной энергии"

![15-11-2018 104649](https://user-images.githubusercontent.com/44586196/48604264-5116af80-e98a-11e8-9891-6c9ab1de0007.jpg)

Не пропал Фреди.

![15-11-2018 104947](https://user-images.githubusercontent.com/44586196/48604265-5116af80-e98a-11e8-837a-8d583019c683.jpg)

**Comment by Regnaris** [comment]
>Это говорит Жонки.

С какой эмоцией?

**Comment by CrewGTW** [comment]
> > Это говорит Жонки.
> 
> С какой эмоцией?

Раздражение.

**Comment by Regnaris** [comment]
Внесены. Закрываю.
