### ISSUE TITLE
Правки 8-12 по версии 3.1 (Не должно быть повторений, но мало ли)

### ISSUE THREAD

**Issue by CrewGTW** [Regnaris/RRS-visualnovel#29]
Девочку уменьшить. Определённо.

![15-11-2018 225407](https://user-images.githubusercontent.com/44586196/48604519-33961580-e98b-11e8-97ca-84792f15854f.jpg)

спросить

![15-11-2018 225620](https://user-images.githubusercontent.com/44586196/48604521-33961580-e98b-11e8-8b24-db726630d721.jpg)

Посты "ты совсем дурак?" заменить на "Ну, раз ты не дорожишь своей энергией, тогда я её заберу."

![15-11-2018 225746](https://user-images.githubusercontent.com/44586196/48604523-342eac00-e98b-11e8-985d-9f1b65677b43.jpg)

На два фрейма.

...

Думаю, ещё вернусь.

![15-11-2018 230108](https://user-images.githubusercontent.com/44586196/48604525-342eac00-e98b-11e8-9863-ffa0ebc48994.jpg)

В диалоговом окне более испуганный спрайт.

![15-11-2018 230338](https://user-images.githubusercontent.com/44586196/48604526-342eac00-e98b-11e8-89d4-cb76a2feef66.jpg)

Завис спрайт.

![15-11-2018 230405](https://user-images.githubusercontent.com/44586196/48604527-342eac00-e98b-11e8-813c-7b29b4eeb64e.jpg)

Надо бы гарпию тогда "отодвинуть"

![15-11-2018 230820](https://user-images.githubusercontent.com/44586196/48604528-34c74280-e98b-11e8-87de-8dcd0088a28f.jpg)

Странное расположение спрайтов.

![15-11-2018 230841](https://user-images.githubusercontent.com/44586196/48604530-34c74280-e98b-11e8-9807-e03533eb10ca.jpg)

Странное расположение спрайтов.

![15-11-2018 231043](https://user-images.githubusercontent.com/44586196/48604531-34c74280-e98b-11e8-955a-1f0524ee0bf5.jpg)

По-твоему, мне силы девать некуда?

![15-11-2018 231157](https://user-images.githubusercontent.com/44586196/48604534-355fd900-e98b-11e8-9852-f662258d8dcf.jpg)

Завис спрайт.

![15-11-2018 231259](https://user-images.githubusercontent.com/44586196/48604535-355fd900-e98b-11e8-9912-29107f1ced94.jpg)

**Comment by CrewGTW** [comment]
> > Посты "ты совсем дурак?" заменить на "Ну, раз ты не дорожишь своей энергией, тогда я её заберу."
> 
> Я не понял чего ты от меня хочешь. Поясни.
> 
> > В диалоговом окне более испуганный спрайт.
> 
> Там CG. Ксения говорила не использовать side image во время CG, так что я просто убрал side image.

После "Пф-ф..." замени текст на "Ну, раз ты не дорожишь своей энергией, тогда я её заберу."


По CG понял.

**Comment by Regnaris** [comment]
Правки внесены. Тема закрыта.
