### ISSUE TITLE
Правки 4.1

### ISSUE THREAD

**Issue by CrewGTW** [Regnaris/RRS-visualnovel#33]
Убрать "состоит".

![23-11-2018 140103](https://user-images.githubusercontent.com/44586196/48966705-f283ae00-efe7-11e8-8e59-aff8785532ee.jpg)

Перенести "Сперва, Стефан..."

![23-11-2018 140437](https://user-images.githubusercontent.com/44586196/48966706-f7e0f880-efe7-11e8-8f27-ac5c54eecaea.jpg)

"Для кого же ещё? Кому о ней заботиться? Пропадёт без хозяйки."

![23-11-2018 140559](https://user-images.githubusercontent.com/44586196/48966711-19da7b00-efe8-11e8-95e0-77f6f3b34469.jpg)

Заменить "клетчатой рубашке красно-чёрных цветов и в чёрной куртке" на "простой серой майке, с накинутой поверх чёрной курткой.

![23-11-2018 140928](https://user-images.githubusercontent.com/44586196/48966716-25c63d00-efe8-11e8-9afe-961fdbb5f459.jpg)

"Вот и ты! Долго же я тебя выслеживал..."

![23-11-2018 141909](https://user-images.githubusercontent.com/44586196/48966719-2a8af100-efe8-11e8-8985-7fc1a0d25da9.jpg)

Убрать фразу вообще.

![23-11-2018 142009](https://user-images.githubusercontent.com/44586196/48966725-3676b300-efe8-11e8-9c2f-816fd99a718e.jpg)

"Не подходи! Второй раз я не смогу тебя спасти!"

![23-11-2018 142059](https://user-images.githubusercontent.com/44586196/48966729-3d052a80-efe8-11e8-9d35-d53068b41804.jpg)

"Кровь пожилого человека может дать такую силу?!"

![23-11-2018 142128](https://user-images.githubusercontent.com/44586196/48966731-41c9de80-efe8-11e8-8d0c-666028c14c1c.jpg)

"Ха-ха-ха... Достали эти ваши суеверия." Новый фрейм "Кровь ценится не по возрасту носителя, а по энергии, которую может дать!"

![23-11-2018 142206](https://user-images.githubusercontent.com/44586196/48966740-6aea6f00-efe8-11e8-9a46-cd6f3256db32.jpg)

Звук воя.

![23-11-2018 142452](https://user-images.githubusercontent.com/44586196/48966742-70e05000-efe8-11e8-8de9-7f87c3760062.jpg)

Перенести со "Спустя..."

![23-11-2018 142654](https://user-images.githubusercontent.com/44586196/48966744-75a50400-efe8-11e8-8eca-49a79d9b2717.jpg)

"Бойтесь своих желаний - они могут сбыться".

![23-11-2018 143710](https://user-images.githubusercontent.com/44586196/48966747-7a69b800-efe8-11e8-98e3-d677d65bb42b.jpg)

Опечатка, "Стефана".

![23-11-2018 143825](https://user-images.githubusercontent.com/44586196/48966749-7e95d580-efe8-11e8-8d88-f0c2b93b820e.jpg)

"Я провёл там слишком мало времени, чтобы что-то понять."

![23-11-2018 143921](https://user-images.githubusercontent.com/44586196/48966752-83f32000-efe8-11e8-821c-84d205a49c7e.jpg)

Немного приблизить фон к углу постройки., убрать спрайты, имитируя то, что они пошли за угол.

![23-11-2018 144120](https://user-images.githubusercontent.com/44586196/48966753-88b7d400-efe8-11e8-9b12-d0c9c7578013.jpg)

Вернуть фон как было.

![23-11-2018 144245](https://user-images.githubusercontent.com/44586196/48966756-8f464b80-efe8-11e8-8c8c-5a0d553c3904.jpg)

"Ты же слышал его? Он считает нас причастными к этому."

![23-11-2018 144330](https://user-images.githubusercontent.com/44586196/48966757-91a8a580-efe8-11e8-8239-321f7c57469e.jpg)

Можно сделать приближение "подползние" спрайта? Увеличением, или как?

![23-11-2018 144706](https://user-images.githubusercontent.com/44586196/48966759-9bcaa400-efe8-11e8-9cc7-b8473cb1182c.jpg)

"Стефан кинул кулон. Ехидна схватила его в воздухе и отбросила в дальний угол крыши за собой."

![23-11-2018 144836](https://user-images.githubusercontent.com/44586196/48966760-9ff6c180-efe8-11e8-8ab3-e61a8d2fa046.jpg)

Можно музыку от начала сцены и до чёрного экрана не прерывать?

![23-11-2018 145004](https://user-images.githubusercontent.com/44586196/48966761-a2f1b200-efe8-11e8-806d-c2e9b8e8654b.jpg)

Звук секретарши.

![23-11-2018 145133](https://user-images.githubusercontent.com/44586196/48966765-a5eca280-efe8-11e8-8f90-fde247ef0d5a.jpg)

Интерфейс как-то пропадает коряво, это можно как-то сгладить и сделать не так заметно?

![23-11-2018 145339](https://user-images.githubusercontent.com/44586196/48966768-aab15680-efe8-11e8-9b4c-e2d9dff536e9.jpg)

Убрать паузу.

![23-11-2018 145555](https://user-images.githubusercontent.com/44586196/48966769-adac4700-efe8-11e8-8be7-c8186b32df46.jpg)

Тут вроде Стефан без плаща в сцене.

![23-11-2018 145922](https://user-images.githubusercontent.com/44586196/48966770-b00ea100-efe8-11e8-81b3-431895fc5031.jpg)

"Рейчил"

![23-11-2018 150223](https://user-images.githubusercontent.com/44586196/48966773-b56beb80-efe8-11e8-93f8-7a0811406b5a.jpg)

"Показывай какой."

![23-11-2018 150832](https://user-images.githubusercontent.com/44586196/48966775-b8ff7280-efe8-11e8-94c8-2cd710204106.jpg)

Пробел.

![23-11-2018 151115](https://user-images.githubusercontent.com/44586196/48966784-bc92f980-efe8-11e8-92b5-b0b246d887aa.jpg)

Пауза лишняя.

![23-11-2018 151213](https://user-images.githubusercontent.com/44586196/48966786-bf8dea00-efe8-11e8-9a5e-484956ade876.jpg)

Перенести на новый фрейм после "мокрые следы."

![23-11-2018 151436](https://user-images.githubusercontent.com/44586196/48966787-c3ba0780-efe8-11e8-9cd8-87f2f6831c18.jpg)

Поправить перенос, поставить после "...".

![23-11-2018 151847](https://user-images.githubusercontent.com/44586196/48966792-c6b4f800-efe8-11e8-9f0a-4f8026737e8b.jpg)

Выбор назвать "Раскритиковать Жонки".

![23-11-2018 152844](https://user-images.githubusercontent.com/44586196/48966795-ccaad900-efe8-11e8-8db9-159328b917d4.jpg)

Не надо паузы.

![23-11-2018 152932](https://user-images.githubusercontent.com/44586196/48966797-ce749c80-efe8-11e8-81c7-10d794a153d2.jpg)

"В том месте..."

![23-11-2018 153022](https://user-images.githubusercontent.com/44586196/48966800-d3395080-efe8-11e8-94d3-267d381565ce.jpg)

Тут после падения чёрный экран, символизирующий проходящее время.

Три фрейма на нём "...", "......" и "........." с паузами.

![23-11-2018 153356](https://user-images.githubusercontent.com/44586196/48966802-d6344100-efe8-11e8-9b81-b88df1cc5ac0.jpg)

Пробел.

![23-11-2018 154235](https://user-images.githubusercontent.com/44586196/48966803-d8969b00-efe8-11e8-8a72-e93fc7044646.jpg)

Не показывать эту форму Жонки в диалоговом окне вообще.

![23-11-2018 154626](https://user-images.githubusercontent.com/44586196/48966807-db918b80-efe8-11e8-9eca-22119bfd4b5f.jpg)

Эффект ЧБ был на школьной раздевалке, а тут нет, хотя тоже прошлое.

![23-11-2018 154825](https://user-images.githubusercontent.com/44586196/48966808-df251280-efe8-11e8-9df3-87a00841268d.jpg)

"Долго же тебя не было..."

![23-11-2018 155113](https://user-images.githubusercontent.com/44586196/48966809-e1876c80-efe8-11e8-8997-d62ff9923d75.jpg)

"Жонки" заменить на "???".

![23-11-2018 155143](https://user-images.githubusercontent.com/44586196/48966810-e5b38a00-efe8-11e8-9ccf-80b1a74bab44.jpg)

"Я уверен, это он мне помог."

![23-11-2018 155224](https://user-images.githubusercontent.com/44586196/48966816-f5cb6980-efe8-11e8-97b0-53c4d092ece6.jpg)

"Он? Кто?"

![23-11-2018 155253](https://user-images.githubusercontent.com/44586196/48966818-f95ef080-efe8-11e8-8cd6-21c3ea25aa39.jpg)

Точку.

![23-11-2018 155318](https://user-images.githubusercontent.com/44586196/48966820-fbc14a80-efe8-11e8-90a7-74d4940a4824.jpg)

Разбить: "он нёс игрушку..." \ "У которой крайне неаккуратно была пришита одна лапа."

![23-11-2018 155544](https://user-images.githubusercontent.com/44586196/48966822-febc3b00-efe8-11e8-979b-3cf5676166dd.jpg)

Добавить фрейм: "Просто подумал, насколько же необычным бывает этот мир..." Эмоция - stefan_joy

![23-11-2018 155720](https://user-images.githubusercontent.com/44586196/48966827-07ad0c80-efe9-11e8-97fe-a9d893c06a27.jpg)

**Comment by Regnaris** [comment]
> Немного приблизить фон к углу постройки., убрать спрайты, имитируя то, что они пошли за угол.

Понимаешь же, что увеличение фона 1920х1080 приведет к размытию? Попробую реализовать, пока вопрос открыт.

> Интерфейс как-то пропадает коряво, это можно как-то сгладить и сделать не так заметно?

Я когда перепишу отрисовку текста посередине эту проблему тоже затрону. Пока будет так.

>Пауза лишняя. (Там где Стефан сказал "Он")

Не могу найти где это

**Comment by CrewGTW** [comment]
> > Немного приблизить фон к углу постройки., убрать спрайты, имитируя то, что они пошли за угол.
> 
> Понимаешь же, что увеличение фона 1920х1080 приведет к размытию? Попробую реализовать, пока вопрос открыт.
> 
> > Интерфейс как-то пропадает коряво, это можно как-то сгладить и сделать не так заметно?
> 
> Я когда перепишу отрисовку текста посередине эту проблему тоже затрону. Пока будет так.
> 
> > Пауза лишняя. (Там где Стефан сказал "Он")
> 
> Не могу найти где это
> 
> Ты скинул еще звуки улицы, но не объяснил, что с ними делать.

Да, приблизить не сильно, процентов на двадцать. Просто "обозначить" это.

Понял.

Найду в новом билде, по правде говоря мне стоило подумать, что так хрен найдёшь.

Про звуки улицы, видимо, потерял. Сохрани их пока, может вспомню, как буду перепроходить.

**Comment by Regnaris** [comment]
Эффект добавил. Правки внесены.
